import { createFakeAIOutput } from "@/lib/fake-ai"
import type {
  AIOutput,
  DocumentBounds,
  Message,
  ReturnField,
  ReviewIssue,
  SourceDocument,
  SourcePointer,
  Task,
  TaxReturn,
  Thread,
  Transformation,
} from "@/mock-data/types"

const primaryBounds: DocumentBounds = {
  x: 96,
  y: 210,
  width: 620,
  height: 48,
}

interface DocumentFixture {
  id: string
  taxReturnId: string
  filename: string
  documentType: SourceDocument["documentType"]
  title: string
  primaryLabel: string
  primaryValue: string
  uploadedAt: string
  uploadedByUserId: string
  processingStatus?: SourceDocument["processingStatus"]
  tags: string[]
  supportingRows?: Array<{ label: string; value: string }>
  secondPageText?: string
}

function makeDocument(fixture: DocumentFixture): SourceDocument {
  const supportingBlocks = (fixture.supportingRows ?? []).map((row, index) => ({
    id: `${fixture.id}-block-${index + 2}`,
    kind: "label-value" as const,
    text: `${row.label}: ${row.value}`,
    label: row.label,
    value: row.value,
    bounds: {
      x: 96,
      y: 282 + index * 54,
      width: 620,
      height: 42,
    },
  }))

  return {
    id: fixture.id,
    taxReturnId: fixture.taxReturnId,
    filename: fixture.filename,
    documentType: fixture.documentType,
    uploadedAt: fixture.uploadedAt,
    uploadedByUserId: fixture.uploadedByUserId,
    processingStatus: fixture.processingStatus ?? "ready",
    taxYear: 2025,
    tags: fixture.tags,
    pages: [
      {
        pageNumber: 1,
        width: 816,
        height: 1056,
        blocks: [
          {
            id: `${fixture.id}-heading`,
            kind: "heading",
            text: fixture.title,
            bounds: { x: 72, y: 72, width: 672, height: 64 },
          },
          {
            id: `${fixture.id}-block-primary`,
            kind: "label-value",
            text: `${fixture.primaryLabel}: ${fixture.primaryValue}`,
            label: fixture.primaryLabel,
            value: fixture.primaryValue,
            bounds: primaryBounds,
          },
          ...supportingBlocks,
        ],
      },
      ...(fixture.secondPageText
        ? [
            {
              pageNumber: 2,
              width: 816,
              height: 1056,
              blocks: [
                {
                  id: `${fixture.id}-block-notes`,
                  kind: "paragraph" as const,
                  text: fixture.secondPageText,
                  bounds: { x: 72, y: 96, width: 672, height: 180 },
                },
              ],
            },
          ]
        : []),
    ],
  }
}

function sourcePointer(
  documentId: string,
  sectionLabel: string,
  blockId = `${documentId}-block-primary`,
  bounds: DocumentBounds = primaryBounds,
): SourcePointer {
  return {
    documentId,
    pageNumber: 1,
    blockId,
    sectionLabel,
    bounds,
  }
}

export const demoSourceDocuments: SourceDocument[] = [
  makeDocument({
    id: "doc-maya-w2",
    taxReturnId: "return-maya-2025",
    filename: "Acme-Design-W2-2025.pdf",
    documentType: "w-2",
    title: "2025 Form W-2",
    primaryLabel: "Box 1 wages",
    primaryValue: "$124,500.00",
    uploadedAt: "2026-03-12T14:18:00-04:00",
    uploadedByUserId: "user-maya-thompson",
    tags: ["income", "wages", "acme-design"],
    supportingRows: [
      { label: "Box 2 federal tax withheld", value: "$22,410.00" },
      { label: "Box 12 code D", value: "$8,750.00" },
    ],
  }),
  makeDocument({
    id: "doc-maya-1099-int",
    taxReturnId: "return-maya-2025",
    filename: "Harbor-Bank-1099-INT.pdf",
    documentType: "1099-int",
    title: "2025 Form 1099-INT",
    primaryLabel: "Box 1 interest income",
    primaryValue: "$842.17",
    uploadedAt: "2026-03-16T09:42:00-04:00",
    uploadedByUserId: "user-maya-thompson",
    tags: ["income", "interest", "harbor-bank"],
  }),
  makeDocument({
    id: "doc-maya-1099-b",
    taxReturnId: "return-maya-2025",
    filename: "Cedar-Investments-1099-B.pdf",
    documentType: "1099-b",
    title: "2025 Form 1099-B",
    primaryLabel: "Total proceeds",
    primaryValue: "$12,800.00",
    uploadedAt: "2026-03-16T09:45:00-04:00",
    uploadedByUserId: "user-maya-thompson",
    tags: ["income", "investments", "capital-gains"],
    supportingRows: [{ label: "Reported cost basis", value: "$9,200.00" }],
  }),
  makeDocument({
    id: "doc-maya-charity",
    taxReturnId: "return-maya-2025",
    filename: "City-Arts-Alliance-receipt.pdf",
    documentType: "receipt",
    title: "City Arts Alliance Donation Receipt",
    primaryLabel: "Contribution amount",
    primaryValue: "$2,400.00",
    uploadedAt: "2026-03-20T11:30:00-04:00",
    uploadedByUserId: "user-maya-thompson",
    tags: ["deduction", "charity"],
    secondPageText:
      "No goods or services were provided in exchange for this contribution.",
  }),
  makeDocument({
    id: "doc-maya-prior-return",
    taxReturnId: "return-maya-2025",
    filename: "Maya-Thompson-2024-Form-1040.pdf",
    documentType: "prior-year-return",
    title: "2024 Form 1040",
    primaryLabel: "Adjusted gross income",
    primaryValue: "$118,930.00",
    uploadedAt: "2026-02-28T16:00:00-05:00",
    uploadedByUserId: "user-mateo-ruiz",
    tags: ["prior-year", "comparison"],
  }),
  makeDocument({
    id: "doc-parkside-1099-k",
    taxReturnId: "return-parkside-2025",
    filename: "Stripe-2025-1099-K.pdf",
    documentType: "1099-k",
    title: "2025 Form 1099-K",
    primaryLabel: "Gross payment amount",
    primaryValue: "$286,400.00",
    uploadedAt: "2026-07-08T10:14:00-04:00",
    uploadedByUserId: "user-elena-park",
    tags: ["income", "payments", "stripe"],
  }),
  makeDocument({
    id: "doc-parkside-pnl",
    taxReturnId: "return-parkside-2025",
    filename: "Parkside-2025-profit-and-loss.pdf",
    documentType: "profit-and-loss",
    title: "Parkside Studio 2025 Profit & Loss",
    primaryLabel: "Net operating income",
    primaryValue: "$118,720.00",
    uploadedAt: "2026-07-08T10:20:00-04:00",
    uploadedByUserId: "user-elena-park",
    tags: ["financials", "profit-loss"],
    supportingRows: [
      { label: "Gross revenue", value: "$292,180.00" },
      { label: "Total operating expenses", value: "$173,460.00" },
    ],
  }),
  makeDocument({
    id: "doc-parkside-lease",
    taxReturnId: "return-parkside-2025",
    filename: "Parkside-studio-lease.pdf",
    documentType: "lease",
    title: "Commercial Lease Summary",
    primaryLabel: "2025 rent paid",
    primaryValue: "$36,000.00",
    uploadedAt: "2026-07-08T10:24:00-04:00",
    uploadedByUserId: "user-elena-park",
    tags: ["expense", "rent"],
  }),
  makeDocument({
    id: "doc-parkside-equipment",
    taxReturnId: "return-parkside-2025",
    filename: "Camera-equipment-invoice.pdf",
    documentType: "invoice",
    title: "Brightline Camera Supply Invoice",
    primaryLabel: "Equipment total",
    primaryValue: "$14,400.00",
    uploadedAt: "2026-07-10T15:40:00-04:00",
    uploadedByUserId: "user-elena-park",
    tags: ["expense", "equipment", "depreciation"],
  }),
  makeDocument({
    id: "doc-parkside-bank",
    taxReturnId: "return-parkside-2025",
    filename: "Parkside-bank-summary-scan.pdf",
    documentType: "bank-statement",
    title: "2025 Business Savings Summary",
    primaryLabel: "Interest credited",
    primaryValue: "$515.09",
    uploadedAt: "2026-07-21T17:09:00-04:00",
    uploadedByUserId: "user-elena-park",
    processingStatus: "needs-review",
    tags: ["income", "interest", "low-quality-scan"],
  }),
  makeDocument({
    id: "doc-mateo-w2",
    taxReturnId: "return-mateo-2025",
    filename: "Hawthorne-Rowe-W2-2025.pdf",
    documentType: "w-2",
    title: "2025 Form W-2",
    primaryLabel: "Box 1 wages",
    primaryValue: "$98,200.00",
    uploadedAt: "2026-02-10T08:12:00-05:00",
    uploadedByUserId: "user-mateo-ruiz",
    tags: ["income", "wages"],
  }),
  makeDocument({
    id: "doc-mateo-1098-e",
    taxReturnId: "return-mateo-2025",
    filename: "Federal-Student-Aid-1098-E.pdf",
    documentType: "1098-e",
    title: "2025 Form 1098-E",
    primaryLabel: "Student loan interest received",
    primaryValue: "$1,480.00",
    uploadedAt: "2026-02-12T13:32:00-05:00",
    uploadedByUserId: "user-mateo-ruiz",
    tags: ["deduction", "student-loan"],
  }),
  makeDocument({
    id: "doc-mateo-charity",
    taxReturnId: "return-mateo-2025",
    filename: "Community-Food-Fund-receipt.pdf",
    documentType: "receipt",
    title: "Community Food Fund Receipt",
    primaryLabel: "Cash contribution",
    primaryValue: "$600.00",
    uploadedAt: "2026-02-14T16:05:00-05:00",
    uploadedByUserId: "user-mateo-ruiz",
    tags: ["deduction", "charity"],
  }),
  makeDocument({
    id: "doc-mateo-1099-int",
    taxReturnId: "return-mateo-2025",
    filename: "Metro-Credit-Union-1099-INT.pdf",
    documentType: "1099-int",
    title: "2025 Form 1099-INT",
    primaryLabel: "Box 1 interest income",
    primaryValue: "$218.00",
    uploadedAt: "2026-02-18T09:10:00-05:00",
    uploadedByUserId: "user-mateo-ruiz",
    tags: ["income", "interest", "corrected-ai"],
  }),
  makeDocument({
    id: "doc-devin-identity",
    taxReturnId: "return-devin-2025",
    filename: "Devin-Foster-drivers-license.pdf",
    documentType: "identity",
    title: "Identity Verification",
    primaryLabel: "Legal name",
    primaryValue: "Devin James Foster",
    uploadedAt: "2026-07-26T12:04:00-04:00",
    uploadedByUserId: "user-devin-foster",
    tags: ["onboarding", "identity"],
  }),
  makeDocument({
    id: "doc-devin-w2",
    taxReturnId: "return-devin-2025",
    filename: "Oak-and-Main-W2-photo.pdf",
    documentType: "w-2",
    title: "2025 Form W-2",
    primaryLabel: "Box 1 wages",
    primaryValue: "$64,000.00",
    uploadedAt: "2026-07-27T08:30:00-04:00",
    uploadedByUserId: "user-devin-foster",
    processingStatus: "processing",
    tags: ["onboarding", "income", "photo"],
  }),
  makeDocument({
    id: "doc-northstar-pnl",
    taxReturnId: "return-northstar-2025",
    filename: "Northstar-consolidated-P-and-L.pdf",
    documentType: "profit-and-loss",
    title: "Northstar 2025 Consolidated Profit & Loss",
    primaryLabel: "Gross revenue",
    primaryValue: "$18,420,000.00",
    uploadedAt: "2026-06-30T18:10:00-04:00",
    uploadedByUserId: "user-nina-patel",
    tags: ["financials", "consolidated", "high-volume"],
  }),
  makeDocument({
    id: "doc-northstar-payroll",
    taxReturnId: "return-northstar-2025",
    filename: "Northstar-2025-payroll-register.pdf",
    documentType: "payroll-report",
    title: "2025 Payroll Register",
    primaryLabel: "Gross payroll",
    primaryValue: "$6,845,310.00",
    uploadedAt: "2026-07-02T12:44:00-04:00",
    uploadedByUserId: "user-nina-patel",
    processingStatus: "needs-review",
    tags: ["payroll", "variance", "high-volume"],
  }),
  makeDocument({
    id: "doc-northstar-assets",
    taxReturnId: "return-northstar-2025",
    filename: "Northstar-fixed-asset-schedule.xlsx.pdf",
    documentType: "fixed-asset-schedule",
    title: "2025 Fixed Asset Schedule",
    primaryLabel: "Current-year additions",
    primaryValue: "$1,182,400.00",
    uploadedAt: "2026-07-03T09:20:00-04:00",
    uploadedByUserId: "user-nina-patel",
    tags: ["assets", "depreciation", "high-volume"],
  }),
  makeDocument({
    id: "doc-northstar-prior-return",
    taxReturnId: "return-northstar-2025",
    filename: "Northstar-2024-1120-S.pdf",
    documentType: "prior-year-return",
    title: "2024 Form 1120-S",
    primaryLabel: "Net operating loss carryforward",
    primaryValue: "$412,000.00",
    uploadedAt: "2026-05-18T11:06:00-04:00",
    uploadedByUserId: "user-alice-chen",
    tags: ["prior-year", "nol", "high-volume"],
  }),
]

const ptr = {
  mayaWages: sourcePointer("doc-maya-w2", "Box 1"),
  mayaInterest: sourcePointer("doc-maya-1099-int", "Box 1"),
  mayaProceeds: sourcePointer("doc-maya-1099-b", "Total proceeds"),
  mayaBasis: sourcePointer(
    "doc-maya-1099-b",
    "Reported cost basis",
    "doc-maya-1099-b-block-2",
    { x: 96, y: 282, width: 620, height: 42 },
  ),
  mayaCharity: sourcePointer("doc-maya-charity", "Contribution amount"),
  parksideGross: sourcePointer("doc-parkside-1099-k", "Gross payment amount"),
  parksideNet: sourcePointer("doc-parkside-pnl", "Net operating income"),
  parksideRent: sourcePointer("doc-parkside-lease", "2025 rent paid"),
  parksideEquipment: sourcePointer(
    "doc-parkside-equipment",
    "Equipment total",
  ),
  parksideInterest: sourcePointer(
    "doc-parkside-bank",
    "Interest credited",
  ),
  mateoWages: sourcePointer("doc-mateo-w2", "Box 1"),
  mateoStudentLoan: sourcePointer(
    "doc-mateo-1098-e",
    "Student loan interest received",
  ),
  mateoCharity: sourcePointer("doc-mateo-charity", "Cash contribution"),
  mateoInterest: sourcePointer("doc-mateo-1099-int", "Box 1"),
  devinName: sourcePointer("doc-devin-identity", "Legal name"),
  devinWages: sourcePointer("doc-devin-w2", "Box 1"),
  northstarRevenue: sourcePointer("doc-northstar-pnl", "Gross revenue"),
  northstarPayroll: sourcePointer("doc-northstar-payroll", "Gross payroll"),
  northstarAssets: sourcePointer(
    "doc-northstar-assets",
    "Current-year additions",
  ),
  northstarNol: sourcePointer(
    "doc-northstar-prior-return",
    "Net operating loss carryforward",
  ),
}

export const demoReturnFields: ReturnField[] = [
  {
    id: "field-maya-wages",
    taxReturnId: "return-maya-2025",
    section: "Income",
    form: "Form 1040",
    locator: "Line 1a",
    label: "Wages, salaries, tips",
    value: 124500,
    displayValue: "$124,500",
    unit: "currency",
    origin: "ai-extracted",
    state: "verified",
    confidence: 96,
    sourcePointers: [ptr.mayaWages],
    aiOutputId: "ai-maya-wages",
    updatedAt: "2026-03-18T10:20:00-04:00",
    updatedByUserId: "user-mateo-ruiz",
  },
  {
    id: "field-maya-interest",
    taxReturnId: "return-maya-2025",
    section: "Income",
    form: "Schedule B",
    locator: "Part I, line 1",
    label: "Taxable interest",
    value: 842.17,
    displayValue: "$842.17",
    unit: "currency",
    origin: "ai-extracted",
    state: "ai-unverified",
    confidence: 74,
    sourcePointers: [ptr.mayaInterest],
    aiOutputId: "ai-maya-interest",
    updatedAt: "2026-03-16T09:47:00-04:00",
    updatedByUserId: "user-mateo-ruiz",
  },
  {
    id: "field-maya-capital-gain",
    taxReturnId: "return-maya-2025",
    section: "Income",
    form: "Schedule D",
    locator: "Line 7",
    label: "Net short-term capital gain",
    value: 3600,
    displayValue: "$3,600",
    unit: "currency",
    origin: "calculated",
    state: "verified",
    sourcePointers: [ptr.mayaProceeds, ptr.mayaBasis],
    transformationId: "transform-maya-capital-gain",
    updatedAt: "2026-03-22T15:05:00-04:00",
    updatedByUserId: "user-mateo-ruiz",
  },
  {
    id: "field-maya-charity",
    taxReturnId: "return-maya-2025",
    section: "Deductions",
    form: "Schedule A",
    locator: "Line 12",
    label: "Cash contributions",
    value: 2400,
    displayValue: "$2,400",
    unit: "currency",
    origin: "client-entered",
    state: "needs-approval",
    sourcePointers: [ptr.mayaCharity],
    updatedAt: "2026-03-20T11:33:00-04:00",
    updatedByUserId: "user-maya-thompson",
  },
  {
    id: "field-parkside-gross-receipts",
    taxReturnId: "return-parkside-2025",
    section: "Income",
    form: "Form 1065",
    locator: "Line 1a",
    label: "Gross receipts or sales",
    value: 286400,
    displayValue: "$286,400",
    unit: "currency",
    origin: "ai-extracted",
    state: "ai-unverified",
    confidence: 92,
    sourcePointers: [ptr.parksideGross],
    aiOutputId: "ai-parkside-gross",
    updatedAt: "2026-07-08T10:26:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-parkside-rent",
    taxReturnId: "return-parkside-2025",
    section: "Deductions",
    form: "Form 1065",
    locator: "Line 13",
    label: "Rent",
    value: 36000,
    displayValue: "$36,000",
    unit: "currency",
    origin: "ai-extracted",
    state: "verified",
    confidence: 98,
    sourcePointers: [ptr.parksideRent],
    updatedAt: "2026-07-12T13:21:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-parkside-depreciation",
    taxReturnId: "return-parkside-2025",
    section: "Deductions",
    form: "Form 4562",
    locator: "Part III",
    label: "Current-year depreciation",
    value: 4800,
    displayValue: "$4,800",
    unit: "currency",
    origin: "calculated",
    state: "needs-approval",
    sourcePointers: [ptr.parksideEquipment],
    transformationId: "transform-parkside-depreciation",
    aiOutputId: "ai-parkside-depreciation",
    updatedAt: "2026-07-14T16:05:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-parkside-interest",
    taxReturnId: "return-parkside-2025",
    section: "Income",
    form: "Form 1065",
    locator: "Line 5",
    label: "Interest income",
    value: 515.09,
    displayValue: "$515.09",
    unit: "currency",
    origin: "ai-extracted",
    state: "ai-unverified",
    confidence: 61,
    sourcePointers: [ptr.parksideInterest],
    aiOutputId: "ai-parkside-interest",
    updatedAt: "2026-07-21T17:12:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-parkside-net-income",
    taxReturnId: "return-parkside-2025",
    section: "Income",
    form: "Form 1065",
    locator: "Line 22",
    label: "Ordinary business income",
    value: 77920,
    displayValue: "$77,920",
    unit: "currency",
    origin: "calculated",
    state: "ai-unverified",
    sourcePointers: [ptr.parksideNet, ptr.parksideRent, ptr.parksideEquipment],
    transformationId: "transform-parkside-net-income",
    updatedAt: "2026-07-14T16:06:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-mateo-wages",
    taxReturnId: "return-mateo-2025",
    section: "Income",
    form: "Form 1040",
    locator: "Line 1a",
    label: "Wages, salaries, tips",
    value: 98200,
    displayValue: "$98,200",
    unit: "currency",
    origin: "ai-extracted",
    state: "locked",
    confidence: 99,
    sourcePointers: [ptr.mateoWages],
    updatedAt: "2026-03-04T10:14:00-05:00",
    updatedByUserId: "user-priya-nair",
  },
  {
    id: "field-mateo-student-interest",
    taxReturnId: "return-mateo-2025",
    section: "Adjustments",
    form: "Schedule 1",
    locator: "Line 21",
    label: "Student loan interest deduction",
    value: 1480,
    displayValue: "$1,480",
    unit: "currency",
    origin: "ai-extracted",
    state: "verified",
    confidence: 97,
    sourcePointers: [ptr.mateoStudentLoan],
    updatedAt: "2026-03-04T10:15:00-05:00",
    updatedByUserId: "user-priya-nair",
  },
  {
    id: "field-mateo-interest",
    taxReturnId: "return-mateo-2025",
    section: "Income",
    form: "Schedule B",
    locator: "Part I, line 1",
    label: "Taxable interest",
    value: 218,
    displayValue: "$218",
    unit: "currency",
    origin: "ai-extracted",
    state: "verified",
    confidence: 88,
    sourcePointers: [ptr.mateoInterest],
    aiOutputId: "ai-mateo-interest-wrong",
    updatedAt: "2026-03-04T10:19:00-05:00",
    updatedByUserId: "user-priya-nair",
  },
  {
    id: "field-mateo-charity",
    taxReturnId: "return-mateo-2025",
    section: "Deductions",
    form: "Schedule A",
    locator: "Line 12",
    label: "Cash contributions",
    value: 600,
    displayValue: "$600",
    unit: "currency",
    origin: "client-entered",
    state: "locked",
    sourcePointers: [ptr.mateoCharity],
    updatedAt: "2026-03-05T09:00:00-05:00",
    updatedByUserId: "user-priya-nair",
  },
  {
    id: "field-devin-filing-status",
    taxReturnId: "return-devin-2025",
    section: "About you",
    form: "Form 1040",
    locator: "Filing status",
    label: "Filing status",
    value: "Single",
    displayValue: "Single",
    unit: "text",
    origin: "client-entered",
    state: "editable",
    sourcePointers: [ptr.devinName],
    updatedAt: "2026-07-26T12:08:00-04:00",
    updatedByUserId: "user-devin-foster",
  },
  {
    id: "field-devin-wages",
    taxReturnId: "return-devin-2025",
    section: "Income",
    form: "Form 1040",
    locator: "Line 1a",
    label: "Wages, salaries, tips",
    value: 64000,
    displayValue: "$64,000",
    unit: "currency",
    origin: "ai-extracted",
    state: "ai-unverified",
    confidence: 45,
    sourcePointers: [ptr.devinWages],
    aiOutputId: "ai-devin-wages",
    updatedAt: "2026-07-27T08:34:00-04:00",
    updatedByUserId: "user-devin-foster",
  },
  {
    id: "field-northstar-revenue",
    taxReturnId: "return-northstar-2025",
    section: "Income",
    form: "Form 1120-S",
    locator: "Line 1a",
    label: "Gross receipts or sales",
    value: 18420000,
    displayValue: "$18,420,000",
    unit: "currency",
    origin: "ai-extracted",
    state: "verified",
    confidence: 97,
    sourcePointers: [ptr.northstarRevenue],
    aiOutputId: "ai-northstar-revenue",
    updatedAt: "2026-07-06T12:00:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-northstar-payroll",
    taxReturnId: "return-northstar-2025",
    section: "Deductions",
    form: "Form 1120-S",
    locator: "Lines 7-8",
    label: "Compensation and wages",
    value: 6845310,
    displayValue: "$6,845,310",
    unit: "currency",
    origin: "ai-extracted",
    state: "needs-approval",
    confidence: 58,
    sourcePointers: [ptr.northstarPayroll],
    aiOutputId: "ai-northstar-payroll-anomaly",
    updatedAt: "2026-07-22T14:45:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-northstar-assets",
    taxReturnId: "return-northstar-2025",
    section: "Depreciation",
    form: "Form 4562",
    locator: "Part III",
    label: "Current-year asset additions",
    value: 1182400,
    displayValue: "$1,182,400",
    unit: "currency",
    origin: "ai-extracted",
    state: "ai-unverified",
    confidence: 83,
    sourcePointers: [ptr.northstarAssets],
    updatedAt: "2026-07-20T09:12:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
  {
    id: "field-northstar-nol",
    taxReturnId: "return-northstar-2025",
    section: "Deductions",
    form: "Form 1120-S",
    locator: "NOL worksheet",
    label: "Net operating loss carryforward",
    value: 412000,
    displayValue: "$412,000",
    unit: "currency",
    origin: "preparer-entered",
    state: "needs-approval",
    sourcePointers: [ptr.northstarNol],
    updatedAt: "2026-07-23T15:02:00-04:00",
    updatedByUserId: "user-alice-chen",
  },
]

export const demoTransformations: Transformation[] = [
  {
    id: "transform-maya-capital-gain",
    taxReturnId: "return-maya-2025",
    returnFieldId: "field-maya-capital-gain",
    explanation: "Sale proceeds minus the broker-reported cost basis.",
    formula: "proceeds - cost basis",
    inputs: [
      {
        label: "Sale proceeds",
        value: 12800,
        displayValue: "$12,800",
        sourcePointer: ptr.mayaProceeds,
      },
      {
        label: "Cost basis",
        value: 9200,
        displayValue: "$9,200",
        sourcePointer: ptr.mayaBasis,
      },
    ],
    steps: [
      {
        order: 1,
        expression: "$12,800 - $9,200",
        result: "$3,600",
      },
    ],
  },
  {
    id: "transform-parkside-depreciation",
    taxReturnId: "return-parkside-2025",
    returnFieldId: "field-parkside-depreciation",
    explanation:
      "Straight-line estimate for the equipment pending reviewer confirmation of the recovery period.",
    formula: "equipment cost / 3 years",
    inputs: [
      {
        label: "Equipment cost",
        value: 14400,
        displayValue: "$14,400",
        sourcePointer: ptr.parksideEquipment,
      },
    ],
    steps: [
      {
        order: 1,
        expression: "$14,400 / 3",
        result: "$4,800",
      },
    ],
  },
  {
    id: "transform-parkside-net-income",
    taxReturnId: "return-parkside-2025",
    returnFieldId: "field-parkside-net-income",
    explanation:
      "Book net income adjusted for separately validated rent and provisional depreciation.",
    formula: "book net income - rent - depreciation",
    inputs: [
      {
        label: "Book net income",
        value: 118720,
        displayValue: "$118,720",
        sourcePointer: ptr.parksideNet,
      },
      {
        label: "Rent",
        value: 36000,
        displayValue: "$36,000",
        sourceFieldId: "field-parkside-rent",
      },
      {
        label: "Provisional depreciation",
        value: 4800,
        displayValue: "$4,800",
        sourceFieldId: "field-parkside-depreciation",
      },
    ],
    steps: [
      {
        order: 1,
        expression: "$118,720 - $36,000",
        result: "$82,720",
      },
      {
        order: 2,
        expression: "$82,720 - $4,800",
        result: "$77,920",
      },
    ],
  },
]

const demoAIOutputFixtures: AIOutput[] = [
  {
    id: "ai-maya-wages",
    kind: "extraction",
    taxReturnId: "return-maya-2025",
    target: { kind: "field", id: "field-maya-wages" },
    recommendation: {
      label: "Use W-2 Box 1 wages",
      proposedValue: 124500,
    },
    confidence: 96,
    summary: "This looks right. 96% confidence from Maya's W-2.",
    why: "The wage label and Box 1 value were clear and matched the form layout.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-maya-w2",
        pageNumber: 1,
        blockId: "doc-maya-w2-block-primary",
        label: "2025 Form W-2, Box 1",
      },
    ],
    reviewStatus: "accepted",
    generatedAt: "2026-03-12T14:19:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-maya-interest",
    kind: "extraction",
    taxReturnId: "return-maya-2025",
    target: { kind: "field", id: "field-maya-interest" },
    recommendation: {
      label: "Use 1099-INT interest income",
      proposedValue: 842.17,
    },
    confidence: 74,
    summary: "Likely $842.17, but the scan should be checked.",
    why: "The value is readable, but light compression artifacts cross the cents.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-maya-1099-int",
        pageNumber: 1,
        blockId: "doc-maya-1099-int-block-primary",
        label: "Harbor Bank 1099-INT, Box 1",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-03-16T09:46:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-parkside-gross",
    kind: "extraction",
    taxReturnId: "return-parkside-2025",
    target: { kind: "field", id: "field-parkside-gross-receipts" },
    recommendation: {
      label: "Use 1099-K gross payments",
      proposedValue: 286400,
    },
    confidence: 92,
    summary: "This looks right. 92% confidence from the 1099-K.",
    why: "The total is clear, but it does not yet reconcile to the books.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-parkside-1099-k",
        pageNumber: 1,
        blockId: "doc-parkside-1099-k-block-primary",
        label: "Stripe 1099-K gross payments",
      },
      {
        kind: "document",
        documentId: "doc-parkside-pnl",
        pageNumber: 1,
        blockId: "doc-parkside-pnl-block-2",
        label: "Book gross revenue",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-07-08T10:25:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-parkside-depreciation",
    kind: "recommendation",
    taxReturnId: "return-parkside-2025",
    target: { kind: "field", id: "field-parkside-depreciation" },
    recommendation: {
      label: "Use a three-year recovery period",
      proposedValue: 4800,
      action: "Confirm asset class before accepting",
    },
    confidence: 72,
    summary: "A $4,800 deduction is plausible, pending asset classification.",
    why: "The invoice shows camera equipment, but it does not state the tax asset class.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-parkside-equipment",
        pageNumber: 1,
        blockId: "doc-parkside-equipment-block-primary",
        label: "Brightline equipment invoice",
      },
      {
        kind: "transformation",
        transformationId: "transform-parkside-depreciation",
        label: "Provisional depreciation calculation",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-07-14T16:04:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-parkside-interest",
    kind: "extraction",
    taxReturnId: "return-parkside-2025",
    target: { kind: "field", id: "field-parkside-interest" },
    recommendation: {
      label: "Use bank interest credited",
      proposedValue: 515.09,
    },
    confidence: 61,
    summary: "I found $515.09, but this needs a human check.",
    why: "The source is a skewed scan and the last two digits are partially obscured.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-parkside-bank",
        pageNumber: 1,
        blockId: "doc-parkside-bank-block-primary",
        label: "Business savings interest",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-07-21T17:11:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-mateo-interest-wrong",
    kind: "extraction",
    taxReturnId: "return-mateo-2025",
    target: { kind: "field", id: "field-mateo-interest" },
    recommendation: {
      label: "Corrected interest income",
      proposedValue: 218,
    },
    confidence: 88,
    summary: "Priya corrected the extraction from $2,180 to $218.",
    why: "The first pass treated the printed decimal and trailing zeros as a thousands grouping.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-mateo-1099-int",
        pageNumber: 1,
        blockId: "doc-mateo-1099-int-block-primary",
        label: "Metro Credit Union 1099-INT, Box 1",
      },
    ],
    reviewStatus: "overridden",
    generatedAt: "2026-02-18T09:11:00-05:00",
    correctionHistory: [
      {
        id: "correction-mateo-interest-1",
        previousRecommendation: {
          label: "Use extracted interest income",
          proposedValue: 2180,
        },
        correctedRecommendation: {
          label: "Use corrected interest income",
          proposedValue: 218,
        },
        reason: "Decimal was misplaced; source Box 1 clearly reads $218.00.",
        correctedByUserId: "user-priya-nair",
        correctedAt: "2026-03-04T10:19:00-05:00",
      },
    ],
  },
  {
    id: "ai-devin-wages",
    kind: "extraction",
    taxReturnId: "return-devin-2025",
    target: { kind: "field", id: "field-devin-wages" },
    recommendation: {
      label: "Tentative W-2 wages",
      proposedValue: 64000,
    },
    confidence: 45,
    summary: "I can make out $64,000, but the photo is still processing.",
    why: "Glare covers part of Box 1 and the image is angled.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-devin-w2",
        pageNumber: 1,
        blockId: "doc-devin-w2-block-primary",
        label: "Oak & Main W-2 photo",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-07-27T08:33:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-northstar-revenue",
    kind: "extraction",
    taxReturnId: "return-northstar-2025",
    target: { kind: "field", id: "field-northstar-revenue" },
    recommendation: {
      label: "Use consolidated gross revenue",
      proposedValue: 18420000,
    },
    confidence: 97,
    summary: "This looks right. 97% confidence from the consolidated P&L.",
    why: "The total is clearly labeled and reconciles across all subsidiary columns.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-northstar-pnl",
        pageNumber: 1,
        blockId: "doc-northstar-pnl-block-primary",
        label: "Consolidated gross revenue",
      },
    ],
    reviewStatus: "accepted",
    generatedAt: "2026-06-30T18:14:00-04:00",
    correctionHistory: [],
  },
  {
    id: "ai-northstar-payroll-anomaly",
    kind: "anomaly",
    taxReturnId: "return-northstar-2025",
    target: { kind: "field", id: "field-northstar-payroll" },
    recommendation: {
      label: "Reconcile payroll variance",
      action: "Compare the payroll register with general ledger accounts 6100-6199",
    },
    confidence: 58,
    summary: "Payroll is $184,700 higher than the general ledger total.",
    why: "The difference may be year-end accruals, but the available documents do not explain it.",
    evidence: [
      {
        kind: "document",
        documentId: "doc-northstar-payroll",
        pageNumber: 1,
        blockId: "doc-northstar-payroll-block-primary",
        label: "2025 payroll register",
      },
      {
        kind: "field",
        fieldId: "field-northstar-payroll",
        label: "Compensation and wages",
      },
    ],
    reviewStatus: "pending-review",
    generatedAt: "2026-07-22T14:44:00-04:00",
    correctionHistory: [],
  },
]

export const demoAIOutputs = demoAIOutputFixtures.map(createFakeAIOutput)

export const demoIssues: ReviewIssue[] = [
  {
    id: "issue-maya-charity-acknowledgment",
    taxReturnId: "return-maya-2025",
    title: "Confirm contemporaneous charity acknowledgment",
    description:
      "The receipt has the amount, but the reviewer needs confirmation that Maya received it before filing.",
    severity: "warning",
    status: "open",
    visibility: "client-visible",
    linkedFieldIds: ["field-maya-charity"],
    linkedDocumentIds: ["doc-maya-charity"],
    ownerUserId: "user-mateo-ruiz",
    createdAt: "2026-07-24T09:12:00-04:00",
  },
  {
    id: "issue-parkside-bank-scan",
    taxReturnId: "return-parkside-2025",
    title: "Unreadable bank statement cents",
    description:
      "Confirm the interest amount or request a clearer statement from the client.",
    severity: "warning",
    status: "open",
    visibility: "client-visible",
    linkedFieldIds: ["field-parkside-interest"],
    linkedDocumentIds: ["doc-parkside-bank"],
    aiOutputId: "ai-parkside-interest",
    ownerUserId: "user-alice-chen",
    createdAt: "2026-07-21T17:13:00-04:00",
  },
  {
    id: "issue-parkside-depreciation",
    taxReturnId: "return-parkside-2025",
    title: "Equipment recovery period needs approval",
    description:
      "The AI suggested three years; a reviewer must confirm the tax classification.",
    severity: "warning",
    status: "open",
    visibility: "internal",
    linkedFieldIds: ["field-parkside-depreciation"],
    linkedDocumentIds: ["doc-parkside-equipment"],
    aiOutputId: "ai-parkside-depreciation",
    ownerUserId: "user-priya-nair",
    createdAt: "2026-07-14T16:07:00-04:00",
  },
  {
    id: "issue-northstar-payroll",
    taxReturnId: "return-northstar-2025",
    title: "Payroll register does not tie to the ledger",
    description:
      "The $184,700 variance blocks reviewer sign-off on compensation.",
    severity: "critical",
    status: "open",
    visibility: "internal",
    linkedFieldIds: ["field-northstar-payroll"],
    linkedDocumentIds: ["doc-northstar-payroll"],
    aiOutputId: "ai-northstar-payroll-anomaly",
    ownerUserId: "user-alice-chen",
    createdAt: "2026-07-22T14:46:00-04:00",
  },
]

export const demoTasks: Task[] = [
  {
    id: "task-maya-confirm-charity",
    title: "Confirm charity acknowledgment date",
    ownerUserId: "user-maya-thompson",
    requestedByUserId: "user-mateo-ruiz",
    taxReturnId: "return-maya-2025",
    links: [
      { kind: "document", id: "doc-maya-charity" },
      { kind: "issue", id: "issue-maya-charity-acknowledgment" },
      { kind: "thread", id: "thread-maya-charity" },
    ],
    dueDate: "2026-07-29T17:00:00-04:00",
    status: "open",
    priority: "high",
    visibility: "client-visible",
  },
  {
    id: "task-parkside-clear-bank-copy",
    title: "Upload a clearer business savings statement",
    ownerUserId: "user-elena-park",
    requestedByUserId: "user-alice-chen",
    taxReturnId: "return-parkside-2025",
    links: [
      { kind: "document", id: "doc-parkside-bank" },
      { kind: "issue", id: "issue-parkside-bank-scan" },
      { kind: "thread", id: "thread-parkside-bank" },
    ],
    dueDate: "2026-07-25T17:00:00-04:00",
    status: "blocked",
    priority: "urgent",
    visibility: "client-visible",
  },
  {
    id: "task-mateo-approve-return",
    title: "Review and approve the completed return",
    ownerUserId: "user-mateo-ruiz",
    requestedByUserId: "user-priya-nair",
    taxReturnId: "return-mateo-2025",
    links: [
      { kind: "field", id: "field-mateo-interest" },
      { kind: "thread", id: "thread-mateo-correction" },
    ],
    dueDate: "2026-07-31T17:00:00-04:00",
    status: "open",
    priority: "normal",
    visibility: "client-visible",
  },
  {
    id: "task-devin-finish-income",
    title: "Confirm your W-2 and add any other income",
    ownerUserId: "user-devin-foster",
    requestedByUserId: "user-mateo-ruiz",
    taxReturnId: "return-devin-2025",
    links: [{ kind: "document", id: "doc-devin-w2" }],
    dueDate: "2026-08-05T17:00:00-04:00",
    status: "in-progress",
    priority: "normal",
    visibility: "client-visible",
  },
  {
    id: "task-northstar-payroll-reconcile",
    title: "Reconcile payroll register to the general ledger",
    ownerUserId: "user-alice-chen",
    requestedByUserId: "user-priya-nair",
    taxReturnId: "return-northstar-2025",
    links: [
      { kind: "document", id: "doc-northstar-payroll" },
      { kind: "issue", id: "issue-northstar-payroll" },
      { kind: "thread", id: "thread-northstar-payroll" },
    ],
    dueDate: "2026-07-28T17:00:00-04:00",
    status: "in-progress",
    priority: "urgent",
    visibility: "internal",
  },
]

export const demoMessages: Message[] = [
  {
    id: "message-maya-charity-request",
    threadId: "thread-maya-charity",
    taxReturnId: "return-maya-2025",
    senderUserId: "user-mateo-ruiz",
    sentAt: "2026-07-24T09:16:00-04:00",
    body: "Was this acknowledgment in your records before April 15?",
    visibility: "client-visible",
    outstandingAction: true,
    linkedEntities: [
      { kind: "document", id: "doc-maya-charity" },
      { kind: "task", id: "task-maya-confirm-charity" },
    ],
  },
  {
    id: "message-maya-charity-reply",
    threadId: "thread-maya-charity",
    taxReturnId: "return-maya-2025",
    senderUserId: "user-maya-thompson",
    sentAt: "2026-07-26T18:40:00-04:00",
    body: "Yes. I received the emailed receipt on December 18 and can forward it.",
    visibility: "client-visible",
    outstandingAction: false,
    linkedEntities: [{ kind: "document", id: "doc-maya-charity" }],
  },
  {
    id: "message-parkside-bank-request",
    threadId: "thread-parkside-bank",
    taxReturnId: "return-parkside-2025",
    senderUserId: "user-alice-chen",
    sentAt: "2026-07-22T08:45:00-04:00",
    body: "Please upload the original PDF. The cents are cut off in this scan.",
    visibility: "client-visible",
    outstandingAction: true,
    linkedEntities: [
      { kind: "document", id: "doc-parkside-bank" },
      { kind: "task", id: "task-parkside-clear-bank-copy" },
    ],
  },
  {
    id: "message-parkside-internal",
    threadId: "thread-parkside-depreciation-internal",
    taxReturnId: "return-parkside-2025",
    senderUserId: "user-alice-chen",
    sentAt: "2026-07-14T16:10:00-04:00",
    body: "The three-year recovery period feels aggressive. Please review before we surface this to Elena.",
    visibility: "internal",
    outstandingAction: true,
    linkedEntities: [
      { kind: "issue", id: "issue-parkside-depreciation" },
      { kind: "field", id: "field-parkside-depreciation" },
    ],
  },
  {
    id: "message-mateo-correction",
    threadId: "thread-mateo-correction",
    taxReturnId: "return-mateo-2025",
    senderUserId: "user-priya-nair",
    sentAt: "2026-03-04T10:21:00-05:00",
    body: "I corrected the interest extraction from $2,180 to $218 and finished review.",
    visibility: "client-visible",
    outstandingAction: true,
    linkedEntities: [
      { kind: "document", id: "doc-mateo-1099-int" },
      { kind: "field", id: "field-mateo-interest" },
      { kind: "task", id: "task-mateo-approve-return" },
    ],
  },
  {
    id: "message-northstar-payroll-internal",
    threadId: "thread-northstar-payroll",
    taxReturnId: "return-northstar-2025",
    senderUserId: "user-priya-nair",
    sentAt: "2026-07-22T15:02:00-04:00",
    body: "Hold compensation review until Alice ties the $184,700 variance.",
    visibility: "internal",
    outstandingAction: true,
    linkedEntities: [
      { kind: "issue", id: "issue-northstar-payroll" },
      { kind: "task", id: "task-northstar-payroll-reconcile" },
    ],
  },
]

export const demoThreads: Thread[] = [
  {
    id: "thread-maya-charity",
    taxReturnId: "return-maya-2025",
    subject: "Charity acknowledgment timing",
    anchor: { kind: "document", id: "doc-maya-charity" },
    visibility: "client-visible",
    participantUserIds: ["user-maya-thompson", "user-mateo-ruiz"],
    messageIds: [
      "message-maya-charity-request",
      "message-maya-charity-reply",
    ],
    outstandingTaskId: "task-maya-confirm-charity",
    lastMessageAt: "2026-07-26T18:40:00-04:00",
  },
  {
    id: "thread-parkside-bank",
    taxReturnId: "return-parkside-2025",
    subject: "Clearer bank statement needed",
    anchor: { kind: "issue", id: "issue-parkside-bank-scan" },
    visibility: "client-visible",
    participantUserIds: ["user-elena-park", "user-alice-chen"],
    messageIds: ["message-parkside-bank-request"],
    outstandingTaskId: "task-parkside-clear-bank-copy",
    lastMessageAt: "2026-07-22T08:45:00-04:00",
  },
  {
    id: "thread-parkside-depreciation-internal",
    taxReturnId: "return-parkside-2025",
    subject: "Equipment recovery period",
    anchor: { kind: "issue", id: "issue-parkside-depreciation" },
    visibility: "internal",
    participantUserIds: ["user-alice-chen", "user-priya-nair"],
    messageIds: ["message-parkside-internal"],
    lastMessageAt: "2026-07-14T16:10:00-04:00",
  },
  {
    id: "thread-mateo-correction",
    taxReturnId: "return-mateo-2025",
    subject: "Interest correction and final approval",
    anchor: { kind: "field", id: "field-mateo-interest" },
    visibility: "client-visible",
    participantUserIds: ["user-mateo-ruiz", "user-priya-nair"],
    messageIds: ["message-mateo-correction"],
    outstandingTaskId: "task-mateo-approve-return",
    lastMessageAt: "2026-03-04T10:21:00-05:00",
  },
  {
    id: "thread-northstar-payroll",
    taxReturnId: "return-northstar-2025",
    subject: "Payroll ledger variance",
    anchor: { kind: "issue", id: "issue-northstar-payroll" },
    visibility: "internal",
    participantUserIds: ["user-alice-chen", "user-priya-nair"],
    messageIds: ["message-northstar-payroll-internal"],
    outstandingTaskId: "task-northstar-payroll-reconcile",
    lastMessageAt: "2026-07-22T15:02:00-04:00",
  },
]

export const demoTaxReturns: TaxReturn[] = [
  {
    id: "return-maya-2025",
    taxYear: 2025,
    clientId: "client-maya-thompson",
    returnType: "individual-1040",
    assignedPreparerId: "user-mateo-ruiz",
    assignedReviewerId: "user-priya-nair",
    status: "in-review",
    statusDetail: "4 fields reviewed; 1 client confirmation remains",
    deadline: "2026-10-15T23:59:00-04:00",
    lastActivityAt: "2026-07-26T18:40:00-04:00",
    returnFieldIds: [
      "field-maya-wages",
      "field-maya-interest",
      "field-maya-capital-gain",
      "field-maya-charity",
    ],
    sourceDocumentIds: [
      "doc-maya-w2",
      "doc-maya-1099-int",
      "doc-maya-1099-b",
      "doc-maya-charity",
      "doc-maya-prior-return",
    ],
    taskIds: ["task-maya-confirm-charity"],
    threadIds: ["thread-maya-charity"],
    issueIds: ["issue-maya-charity-acknowledgment"],
    statusHistory: [
      {
        status: "in-preparation",
        changedAt: "2026-03-12T14:20:00-04:00",
        changedByUserId: "user-mateo-ruiz",
      },
      {
        status: "in-review",
        changedAt: "2026-07-24T09:10:00-04:00",
        changedByUserId: "user-mateo-ruiz",
        detail: "Submitted to Priya for review",
      },
    ],
  },
  {
    id: "return-parkside-2025",
    taxYear: 2025,
    clientId: "client-parkside-studio",
    returnType: "partnership-1065",
    assignedPreparerId: "user-alice-chen",
    assignedReviewerId: "user-priya-nair",
    status: "awaiting-client-info",
    statusDetail: "Blocked on a readable business savings statement",
    deadline: "2026-09-15T23:59:00-04:00",
    lastActivityAt: "2026-07-22T08:45:00-04:00",
    waitingSince: "2026-07-22T08:45:00-04:00",
    returnFieldIds: [
      "field-parkside-gross-receipts",
      "field-parkside-rent",
      "field-parkside-depreciation",
      "field-parkside-interest",
      "field-parkside-net-income",
    ],
    sourceDocumentIds: [
      "doc-parkside-1099-k",
      "doc-parkside-pnl",
      "doc-parkside-lease",
      "doc-parkside-equipment",
      "doc-parkside-bank",
    ],
    taskIds: ["task-parkside-clear-bank-copy"],
    threadIds: [
      "thread-parkside-bank",
      "thread-parkside-depreciation-internal",
    ],
    issueIds: [
      "issue-parkside-bank-scan",
      "issue-parkside-depreciation",
    ],
    statusHistory: [
      {
        status: "in-preparation",
        changedAt: "2026-07-08T10:30:00-04:00",
        changedByUserId: "user-alice-chen",
      },
      {
        status: "awaiting-client-info",
        changedAt: "2026-07-22T08:45:00-04:00",
        changedByUserId: "user-alice-chen",
        detail: "Requested original business savings statement",
      },
    ],
  },
  {
    id: "return-mateo-2025",
    taxYear: 2025,
    clientId: "client-mateo-ruiz",
    returnType: "individual-1040",
    assignedPreparerId: "user-alice-chen",
    assignedReviewerId: "user-priya-nair",
    status: "client-approval-needed",
    statusDetail: "Review is complete; Mateo needs to approve filing",
    deadline: "2026-10-15T23:59:00-04:00",
    lastActivityAt: "2026-07-25T11:14:00-04:00",
    waitingSince: "2026-07-25T11:14:00-04:00",
    returnFieldIds: [
      "field-mateo-wages",
      "field-mateo-student-interest",
      "field-mateo-interest",
      "field-mateo-charity",
    ],
    sourceDocumentIds: [
      "doc-mateo-w2",
      "doc-mateo-1098-e",
      "doc-mateo-charity",
      "doc-mateo-1099-int",
    ],
    taskIds: ["task-mateo-approve-return"],
    threadIds: ["thread-mateo-correction"],
    issueIds: [],
    statusHistory: [
      {
        status: "in-review",
        changedAt: "2026-03-03T09:00:00-05:00",
        changedByUserId: "user-alice-chen",
      },
      {
        status: "client-approval-needed",
        changedAt: "2026-07-25T11:14:00-04:00",
        changedByUserId: "user-priya-nair",
        detail: "Reviewer approved the corrected return",
      },
    ],
  },
  {
    id: "return-devin-2025",
    taxYear: 2025,
    clientId: "client-devin-foster",
    returnType: "individual-1040",
    assignedPreparerId: "user-mateo-ruiz",
    assignedReviewerId: "user-priya-nair",
    status: "not-started",
    statusDetail: "Onboarding is 1 of 4 steps complete",
    deadline: "2026-10-15T23:59:00-04:00",
    lastActivityAt: "2026-07-27T08:34:00-04:00",
    returnFieldIds: ["field-devin-filing-status", "field-devin-wages"],
    sourceDocumentIds: ["doc-devin-identity", "doc-devin-w2"],
    taskIds: ["task-devin-finish-income"],
    threadIds: [],
    issueIds: [],
    statusHistory: [
      {
        status: "not-started",
        changedAt: "2026-07-26T12:00:00-04:00",
        changedByUserId: "user-devin-foster",
        detail: "Client accepted invitation",
      },
    ],
  },
  {
    id: "return-northstar-2025",
    taxYear: 2025,
    clientId: "client-northstar-manufacturing",
    returnType: "corporation-1120-s",
    assignedPreparerId: "user-alice-chen",
    assignedReviewerId: "user-priya-nair",
    status: "in-preparation",
    statusDetail: "Document review is 68% complete; payroll variance blocks review",
    deadline: "2026-09-15T23:59:00-04:00",
    lastActivityAt: "2026-07-27T09:05:00-04:00",
    returnFieldIds: [
      "field-northstar-revenue",
      "field-northstar-payroll",
      "field-northstar-assets",
      "field-northstar-nol",
    ],
    sourceDocumentIds: [
      "doc-northstar-pnl",
      "doc-northstar-payroll",
      "doc-northstar-assets",
      "doc-northstar-prior-return",
    ],
    taskIds: ["task-northstar-payroll-reconcile"],
    threadIds: ["thread-northstar-payroll"],
    issueIds: ["issue-northstar-payroll"],
    statusHistory: [
      {
        status: "in-preparation",
        changedAt: "2026-06-30T18:20:00-04:00",
        changedByUserId: "user-alice-chen",
        detail: "Bulk document review started",
      },
    ],
  },
]
